### ISSUE TITLE
Second copy of server loops forever

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#11]
Using Windows PowerShell. Run 'start npm start' once and all is fine. 

Run 'start npm start' again and it produces an error message, and then loops forever. The error message is:
```
Port 2000 is already in use
Program node ./bin/www exited with code 1
```

**Comment by evoluteur** [comment]
The looping for ever is b/c I use supervisor to automatically restart after a crash.
If you do not want that behavior, you can change the start script in package.json for "./bin/www" or simply run "./bin/www" instead of "npm start".
