### ISSUE TITLE
Server error on upload due to undefine variable

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#12]
This line of code triggers an error on upload (upload.js:51):
            `logger.logSuccess('Saving File: "'+ffname+'".')`

This seems to fix it.
`            logger.logSuccess('Saving File: "'+fname+'".')`

**Comment by evoluteur** [comment]
I think the fix is to add a callback as a 3rd parameter.
fs.rename(file.path, ffname, function (err) {
   if (err) throw err;
});
That seems to work fine on my Mac (I also did a little bit of code cleanup). Please let me know if it fix the problem on Windows.
