### ISSUE TITLE
Collection API sorts in wrong order

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#13]
The collection API function uses this SQL:

```
    sql = 'SELECT t1.id, '+sqls.select(collec.fields)+
         ' FROM '+schema+'."'+collec.table+'" AS t1'+
         ' WHERE t1."'+collec.column+'"=$1'+
         ' ORDER BY t1.id'+//t1.position, t1.id
         ' LIMIT '+defaultPageSize+';';
```
The ORDER BY on t1.id looks incorrect. See the collections panel for 'Vine Cliff' for an example.
It looks like it should be `collec.fields[0].id', or something like that. 

Note: there doesn't seem to be any way to sort collections to a desired order.

**Comment by evoluteur** [comment]
Thanks. Fixed.
