### ISSUE TITLE
Dates are off by one

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#17]
To give an example, for issue 'Add sample data' 
 - in the JS data the due date is 2018-04-23. 
 - In the Postgres database it is the same: 2018-04-23. 
 - But in the UI it shows as '04/22/2018'. 
 - Using a debugger, the wire format is '2018-04-22T14:00:00.000Z'.

So where did the '14' come from? Time zone difference?

**Comment by evoluteur** [comment]
Using the following SQL will fix it:
SET TIMEZONE='America/Los_Angeles';
