### ISSUE TITLE
Setting PORT overrides apiPort but does not display

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#19]
Setting PORT overrides apiPort but does not display

In www:
`var port = normalizePort(process.env.PORT || config.apiPort || '3000');`

In logger.js:
`const apiRoot = 'http://localhost:'+config.apiPort+config.apiPath;`

Solution: remove this logic from www, just rely on config.js.
`var port = config.apiPort`

**Comment by evoluteur** [comment]
Done.
