### ISSUE TITLE
using panel-list

### ISSUE THREAD

**Issue by shanequint** [evoluteur/evolutility-server-node#2]
I have created a tedius version of the evolutility-server that is working great for a single table.  I was wondering how I could use the panel-list to display a master-detail.  I have patient data in the main table and would like to display visits, medications, symptoms, diagnoses. How would I model this in the UI-model?  Any help would be greatly appreciated.

**Comment by evoluteur** [comment]
Can you do it the same way than the "wine cellar" example?

**Comment by shanequint** [comment]
Sorry I didn't get back earlier.  I changed approaches and am now trying to use the field type of list for symptoms a patient might have as a test.  I created a Symptoms column in my patient table and populated it with a comma separated list of Symptom ids like ['1', '3', '28', '44'] that correspond to various symptoms such as 
list: [ {id: '1', text: 'Anxiety'}, {id: '2', text: 'Headaches'}, {id:'3', text: 'Sleeplessness'} ...]
The result in the UI is a blank set of Symptoms just multiple commas like , , , , 
I don't know if it is SQL Server and the tedius driver I am using or something else.  

Any thoughts?

Thanks,

**Comment by evoluteur** [comment]
I'm not fully finished w/ it yet. I'm hoping to have it soon.

**Comment by evoluteur** [comment]
Using a column of type Text[] seems to work.

**Comment by evoluteur** [comment]
I still have a little work to do. It will be ready in the next few days.

**Comment by shanequint** [comment]
Thanks, I appreciate it.  I really enjoy how it works thus far.

**Comment by evoluteur** [comment]
"list" fields are working. "panel-list" is not implemented yet.

**Comment by shanequint** [comment]
I have the "list" fields displaying, but it seems to be not showing all of the items in the list.  It is not displaying the first or last item in the database field.  (i.e. [1, 3, 10]  would display item 3 only with empty divs for the first and last items.  Also, The filter doesn't seem to work for list fields. 

Any Ideas on these items?

Thanks!

**Comment by evoluteur** [comment]
I may have change the column type since the previous version. Make sure the column is of type "text array" and the list has ids as strings.
