### ISSUE TITLE
Setup database now fails with duplicate column "parent_id"

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#20]
The fix is easy: just give the field a different column name such as:
```
{
  		"id": "parent",
  		"type": "lov",
  		"label": "Parent",
  		"object": "test",
		"required": true,
		"inMany": true,
		"column": "f_parent",
		//"column": "parent_id",
		"lovtable": "z_test"
},
```

The test table doesn't show up on the menu, so it's not easy to check if the fixed data works ok.

**Comment by evoluteur** [comment]
It is working fine. It may have been fixed by some other changes.
