### ISSUE TITLE
Extra 

### ISSUE THREAD

**Issue by suzeeparker** [evoluteur/evolutility-server-node#24]
Hi Oliver, 

I have just discovered your work.  I wrote an "model-driven" data entry form for my buddy long ago in ASP.VB.  It's been running happily since then.   But he needs to upgrade it.  Your work seems to be just the answer.  My buddy will look at your ASP.Net version.  We wish we had found it earlier. 

I, on the other hand, have moved on to NodeJS and React.  I was able to get the UI-React app to install and run with no problem, although I haven't figured out how to access the localdata store.  

But, I am more interested in the server-side app, DB-Server, that I guess you have recently written.  I have found a trivial error:  an extra }) and } in the script, query.js.  After removing them, it runs fine. 

Thanks, keep up the great work. 

Sue Parker

 ```
          .catch(err => {
                console.log(err.stack)
                errors.badRequest(res, 'Database error.', 500)
            })
    })
}   

    });  // Declaration or statement expected.
} // Declaration or statement expected.

// --------------------------------------------------------------------------------------
module.exports = {
    runQuery: runQuery,
}
```

![bt90413)_Evolutility-Error](https://user-images.githubusercontent.com/32445257/56086712-b6cc7200-5e2a-11e9-8539-fecff2ebceb9.png)

**Comment by evoluteur** [comment]
Thanks a lot for letting me know. Fixed.

**Comment by evoluteur** [comment]
BTW, one my my first model-driven app was in VB.net. VB is great.
