### ISSUE TITLE
NOT AN ISSUE - Active Directory integration with Multi-User row level security

### ISSUE THREAD

**Issue by pymeup** [evoluteur/evolutility-server-node#29]
Hi Olivier,

Hope to find you well!

I am coming back after a few months to you with a new curiosity and possible collaboration.

I am currently looking at the Multi-User row level security demo and I would like to know if Active Directory integration is possible, or if you have encountered this request along the way and maybe have some workarounds?

This question comes in the context of a possible new project I will be working on where we are aiming to use Evolutility and Pentaho to build a login portal and use the multi-user app to control the data each user can access along with other ETL logic.

If we manage to integrate this, we will be more than happy to take things further and discuss commercial licensing.

Kindly let me know your thoughts on this!

All the best,
Costin Valeanu

**Comment by evoluteur** [comment]
Hi Costin,

I have o plan to integrate Active Directory. It has been asked many times over the years though...
Only the ASP.net version of Evolutility supports row level security.

Regards,
Olivier

**Comment by pymeup** [comment]
Hi Olivier,

Many thanks for your reply!

Do you have any estimate or a timeline for the Active Directory integration?

All the best,
Costin

**Comment by evoluteur** [comment]
Oops sorry for the typo. I have no plan for active directory at this time. 
There are a lot of other feature I would want to do before and I have limited time...
