### ISSUE TITLE
Hooks for CRUD events?

### ISSUE THREAD

**Issue by jptarqu** [evoluteur/evolutility-server-node#4]
Hi is there a way to provide code to run before or after CRUD events?
For example running code before a model is inserted in the db to update that model's "OrderSartedDate" to today's date (a very minimalistic example, but you probably get the idea)?

Thank you!

**Comment by evoluteur** [comment]
A few hooks would be useful indeed but I do not currently have them in place. Right now I only have a naive implementation. 
It may be possible to do it in the database with functions and triggers.
