### ISSUE TITLE
Files created with names illegal on Windows

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#6]
The files created at database.js:220 contain colons, which are not allowed on Windows.
This line causes the problem:
    `var fId = new Date().toISOString()`

Here is a simple patch:
    `var fId = new Date().toISOString().replace(/:/g,'')`

**Comment by evoluteur** [comment]
Somehow this issue was entered twice. I'm closing this one as duplicate.

**Comment by david-pfx** [comment]
Yes, a very odd thing happened. GitHub died while I was entering the issue. I thought it was a problem my end so I entered it again (you’ll see the wording is not identical). I only found out later that it was a GitHub outage.

 

Regards

David M Bennett FACS

  _____  

Puzzlang – Pattern language and Unity player for abstract single-player games and puzzles  -- http://www.polyomino.com <http://www.polyomino.com/>
