### ISSUE TITLE
Export produces CSV files in unfriendly format

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#9]
The export feature produces UTF-8 files with long verbose dates. They do not import at all easily into common tools such as Excel.
For easy import into Excel (and other tools) the ideal would be tab delimited, either ANSI or UTF-8 with BOM mark, and with a short culture-neutral date/time format.

**Comment by david-pfx** [comment]
Suggest switching from express-csv (which is no longer being supported or updated) to csv-express (a fork resolving some outstanding issues). It behaves better with Excel, and provides options for encodings and different delimiters.

**Comment by evoluteur** [comment]
OK, I just made the switch to csv-express.
